import song from './song';
import CPlayer from './player-small';

let musicAudio = { play: () => {} };

function loadSong() {
  const player = new CPlayer();
  player.init(song);

  let loaded = 0;
  while (loaded < 1) {
    loaded = player.generate();
    console.log(`loaded ${loaded * 100}%`);
  }

  let wave = player.createWave();
  return [
    document.createElement('audio'),
    URL.createObjectURL(new Blob([wave], {type:'audio/wav'})),
  ]
};

// Music wrapper API


export const loadSongs = () => {
  [audio, data] = loadSong();
  musicAudio = audio;
  musicAudio.src = data;
  musicAudio.loop = true;
  musicAudio.volume = 0.15;
}

/**
 * Play a ZzFX Music song
 * @param {*} songData song data generated by loadSongs/zzfxM
 * @returns an Audio Node to control the song playing (and stop if for example)
 */
export const playSong = () => { musicAudio.play() };

export const stopSong = () => { musicAudio.pause() };
